name: various variables workflow

env:
  workflow_level_var: "workflow_env_var"

on: workflow_dispatch


jobs:
  env-vars:
    env:
      job_level_var: "job_level_var"
    runs-on: ubuntu-latest
    steps:
      - name: workflow level var
        run: echo "$workflow_level_var"
        env:
          step_level_var: "step_level_var"
      - name: job level env var
        run: echo "$job_level_var"
      - name: step level var
        run: echo "$step_level_var"
        
