name: various variables workflow

env:
  workflow_level_var: "workflow_env_var"

on: workflow_dispatch


jobs:
  env-vars:
    env:
      job_level_var: "job_level_var"
    runs-on: ubuntu-latest
    steps:
      - name: workflow level var
        run: echo "$workflow_level_var"
      - name: job level env var
        run: |
          echo "job:: $job_level_var"
          echo "step:::$step_level_var"
        env:
          step_level_var: "step_level_var"
      - name: step level var
        run: echo "step:::$step_level_var"
  second-type-vars:
    runs-on: ubuntu-latest
    steps: 
      - name: create variable
        run: |
          echo "VERSION=1.2.3" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: User variable
        run: |
          echo "$VERSION"
          echo "$BUILD_DATE"
        
      - name: full object GITHUB_ENV
        run: echo "$GITHUB_ENV"


  output-build:
    runs-on: ubuntu-latest
    outputs:
      firstName: ${{steps.firstname.outputs.firstname}}
    steps:
      - name: print something
        run: echo "something"
      - id: firstname
        run: echo "firstname=shamshad" >> $GITHUB_OUTPUT
  output-deploy:
    needs: output-build
    runs-on: ubuntu-latest
    steps:
      - name: get output variable
        run: echo "${{needs.output-build.outputs.firstName}}"
      - id: firstname
        run: echo "firstname=shamshad" >> $GITHUB_OUTPUT
 

    
